name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'   # Pilihan distribusi, bisa 'adopt', 'zulu', 'temurin', dll.
          java-version: '11'      # Versi JDK yang dibutuhkan, misalnya 11

      - name: Build with Gradle
        run: ./gradlew build
